---
- hosts: all
  become: yes

  tasks:
  - name: install php-dom
    yum: name=php-dom state=latest

  - name: install aws-cli
    yum: name=aws-cli state=latest

  - name: install wp-cli
    shell: curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
    args:
      chdir: /root
      creates: wp-cli.phar

  - name: creates wpbackup dir
    file: path=/tmp/wpbackups state=directory

  - cron:
      name=make_wp_backup 
      minute=0
      hour=22
      weekday=2
      job="php /root/wp-cli.phar export --path=/var/www/html --dir=/tmp/wpbackups"
      state=present

  - cron: 
      name=copy_wp_backups
      minute=0 
      hour=23 
      weekday=2 
      job="aws s3 sync /tmp/wpbackups s3://ihiwpbackups/" 
      state=present


  - lineinfile:
      dest: /var/www/html/wp-config.php
      regexp: 'DBI_AWS_ACCESS_KEY_ID'
      backrefs: no
      state: present
      line: "define( \"DBI_AWS_ACCESS_KEY_ID\", \"{{ lookup('env','AS3CF_KEY') }}\" );"

  - lineinfile:
      dest: /var/www/html/wp-config.php
      regexp: 'DBI_AWS_SECRET_ACCESS_KEY'
      backrefs: no
      state: present
      line: "define( \"DBI_AWS_SECRET_ACCESS_KEY\", \"{{ lookup('env','AS3CF_SECRET') }}\" );"

  - file:
      src: /eternalfiles/files/
      dest: /var/www/html/files
      state: link


  - file:
      path: /var/www/html/sitemap.xml
      owner: apache

  - file:
      path: /var/www/html/sitemap.xml.gz
      owner: apache


  - lineinfile:
      dest: /var/www/html/a_simple_pingdom_test.php
      regexp: '^\$DB_HOST'
      backrefs: no
      state: present
      line: "$DB_HOST = \"{{ lookup('env','ihi_host') }}\"; "

  - lineinfile:
      dest: /var/www/html/a_simple_pingdom_test.php
      regexp: '^\$DB_USER'
      backrefs: no
      state: present
      line: "$DB_USERNAME = \"{{ lookup('env','ihi_user') }}\"; "

  - lineinfile:
      dest: /var/www/html/a_simple_pingdom_test.php
      regexp: '^\$DB_PASS'
      backrefs: no
      state: present
      line: "$DB_PASSWORD = \"{{ lookup('env','ihi_pass') }}\"; "
